HMA-5069: Heading (Atom)
hmrc/android-components pull request #100
Opened 2023-02-09 17:46 UTC by sajinabraham

# 📝 Description
Compose Heading (Atom)

Github Issue
https://jira.tools.tax.service.gov.uk/browse/HMA-5069
  
- [ ] Updated CHANGELOG
- [ ] Updated README

# 🛠 Testing Notes

# 📸 Screenshots

2023-02-10 12:34 UTC, jemmaSlater requested changes

2023-02-10 12:34 UTC, jemmaSlater commented on components-compose/src/main/java/uk/gov/hmrc/components/compose/ui/theme/Type.kt
> +    )
Please can we add the colour here as otherwise `info` text has the same definition as body. The `info` text should always have color `grey1`.

2023-02-10 12:34 UTC, jemmaSlater commented on sample-compose-fragments/src/main/java/uk/gov/hmrc/sample_compose_fragments/presentation/screens/TextScreen.kt
> +        )
I think we can make `errorText` one of the `HmrcTypography` types and declare it explicitly.

2023-02-10 12:34 UTC, jemmaSlater commented on sample-compose-fragments/src/main/res/navigation/nav_graph.xml
>          tools:layout="@layout/fragment_atoms"/>
Please can we split this out into a `nav_graph_atoms` then include it here instead, so we have a similar structure to the main app? Then the `TextFragment` declaration can live inside the atoms graph.

2023-02-10 12:34 UTC, jemmaSlater commented on components-compose/src/main/java/uk/gov/hmrc/components/compose/extensions/HtmlTextExt.kt
> +                            CustomAccessibilityAction("Link (${annotatedString.substring(it.start, it.end)})") {
We don't want any hardcoded text in the component library! (incase we need to support translations, etc.)

2023-02-10 12:34 UTC, jemmaSlater commented on components-compose/src/main/java/uk/gov/hmrc/components/compose/extensions/HtmlTextExt.kt
> +fun HtmlText(
Checked with the designers and we don't need to include HtmlText for now, so we can get rid of this class! :)

2023-02-12 21:07 UTC, sajinabraham commented on sample-compose-fragments/src/main/java/uk/gov/hmrc/sample_compose_fragments/presentation/MainActivity.kt
> +    }
i think navigation graph still needed for back-button and our main app uses the same?

2023-02-13 13:39 UTC, jemmaSlater approved these changes

2023-02-13 14:53 UTC, ngoulongkam approved these changes

2023-02-14 17:01 UTC, merged