HMA-6086 ELV view state
hmrc/android-components pull request #101
Opened 2023-02-13 15:40 UTC by emmaatkins

# 📝 Description

Github Issue
HMA-6086
  
- [x] Updated CHANGELOG
- [ ] Updated README

# 🛠 Testing Notes
Functions should be identical to previous EditableListView - backend changes made only.
Changes to donut animation

# 📸 Screenshots

2023-02-13 16:00 UTC, jemmaSlater submitted a review, later dismissed

2023-02-15 10:20 UTC, ngoulongkam submitted a review, later dismissed

2023-02-15 10:48 UTC, ngoulongkam approved these changes

2023-02-16 14:19 UTC, ngoulongkam requested changes

2023-02-16 14:19 UTC, ngoulongkam commented on CHANGELOG.md
> +* `EditableListView` changed to use `EditableListItemViewState`.
maybe also mention here what you've done for DonutChartView.

2023-02-16 14:19 UTC, ngoulongkam commented on sample/src/main/res/values/strings.xml
> +<resources xmlns:tools="http://schemas.android.com/tools">
Dont think this is needed

2023-02-17 10:09 UTC, ngoulongkam approved these changes

2023-02-17 10:13 UTC, merged