Separated View Container Fragment, Screen, View, View model added
hmrc/android-components pull request #148
Opened 2023-11-02 13:10 UTC by aliahmedbd

# 📝 Description
https://jira.tools.tax.service.gov.uk/browse/HMA-5070
  
- [ ] Updated CHANGELOG
- [ ] Updated README

# 📸 Screenshots
<img width="549" alt="Screenshot 2023-11-02 at 13 04 36" src="https://github.com/hmrc/android-components/assets/11981999/e6c86b54-b4dd-4b1a-9143-714aa08a425c">

2023-11-17 14:36 UTC, ngoulongkam requested changes

2023-11-20 10:35 UTC, jemmaSlater commented on sample-compose-fragments/src/main/java/uk/gov/hmrc/sample_compose_fragments/presentation/fragment/organisms/SeparateViewContainerFragment.kt
> +class SeparateViewContainerFragment : Fragment(R.layout.fragment_compose_example) {
I'm being quite picky here, but can we call this file `SeparatedViewContainerFragment` for consistency? :) 
```suggestion
class SeparatedViewContainerFragment : Fragment(R.layout.fragment_compose_example) {
```

2023-11-20 10:35 UTC, jemmaSlater commented on sample-compose-fragments/src/main/res/navigation/nav_graph.xml
> +        android:name="uk.gov.hmrc.sample_compose_fragments.presentation.fragment.organisms.SeparateViewContainerFragment"
```suggestion
        android:id="@+id/separatedViewContainerFragment"
        android:name="uk.gov.hmrc.sample_compose_fragments.presentation.fragment.organisms.SeparatedViewContainerFragment"
```

2023-11-20 13:56 UTC, jemmaSlater approved these changes

2023-11-20 14:24 UTC, ngoulongkam approved these changes

2023-11-21 11:48 UTC, merged